//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int favorite_id { get; set; }
        public Nullable<bool> favorite_active { get; set; }
        public Nullable<bool> favorite_option { get; set; }
        public Nullable<bool> favorite_bin { get; set; }
        public Nullable<System.DateTime> favorite_datecreate { get; set; }
        public Nullable<System.DateTime> favorite_dateupdate { get; set; }
        public Nullable<int> music_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Music Music { get; set; }
        public virtual User User { get; set; }
    }
}
