//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class National
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public National()
        {
            this.MusicsLists = new HashSet<MusicsList>();
        }
    
        public int nation_id { get; set; }
        public string nation_name { get; set; }
        public Nullable<bool> nation_active { get; set; }
        public Nullable<bool> nation_bin { get; set; }
        public Nullable<System.DateTime> nation_datecreate { get; set; }
        public Nullable<System.DateTime> nation_dateupdate { get; set; }
        public Nullable<bool> nation_option { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicsList> MusicsLists { get; set; }
    }
}
