//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayList
    {
        public int playlist_id { get; set; }
        public Nullable<int> albums_id { get; set; }
        public Nullable<int> music_id { get; set; }
        public Nullable<System.DateTime> playlist_datecreate { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Music Music { get; set; }
    }
}
