//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quest()
        {
            this.QuestGroups = new HashSet<QuestGroup>();
        }
    
        public int quest_id { get; set; }
        public Nullable<int> quest_limit { get; set; }
        public Nullable<System.DateTime> quest_datecreate { get; set; }
        public Nullable<System.DateTime> quest_dateend { get; set; }
        public Nullable<bool> quest_active { get; set; }
        public Nullable<int> quest_category { get; set; }
        public Nullable<int> quest_national { get; set; }
        public Nullable<int> quest_singer { get; set; }
        public string quest_gift { get; set; }
        public string quest_top1 { get; set; }
        public string quest_top2 { get; set; }
        public string quest_top3 { get; set; }
        public string quest_title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestGroup> QuestGroups { get; set; }
    }
}
