//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestGroup
    {
        public int qg_id { get; set; }
        public Nullable<int> quest_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> qg_datecreate { get; set; }
    
        public virtual Quest Quest { get; set; }
        public virtual User User { get; set; }
    }
}
