//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int slider_id { get; set; }
        public string slider_img { get; set; }
        public string slider_name { get; set; }
        public string slider_link { get; set; }
        public Nullable<System.DateTime> slider_datecreate { get; set; }
        public Nullable<bool> slider_active { get; set; }
    }
}
