//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int video_id { get; set; }
        public string video_name { get; set; }
        public Nullable<bool> video_active { get; set; }
        public Nullable<bool> video_option { get; set; }
        public Nullable<bool> video_bin { get; set; }
        public Nullable<System.DateTime> video_datecreate { get; set; }
        public Nullable<System.DateTime> video_dateupdate { get; set; }
        public Nullable<int> video_view { get; set; }
        public Nullable<int> video_favorite { get; set; }
        public Nullable<int> music_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Music Music { get; set; }
        public virtual User User { get; set; }
    }
}
